apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: submission-portal-spc
  namespace: submission-portal
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.infra-vault.svc.cluster.local:8200"
    roleName: "submission-portal-role"
    objects: |
      - objectName: "oidc-client-secret"
        secretPath: "submission-portal/data/oidc-client"
        secretKey: "client-secret"
