apiVersion: v1
kind: Service
metadata:
  name: postgres-unit2
  namespace: submission-portal
  labels:
    app: postgres
    unit: unit2
spec:
  selector:
    app: postgres
    unit: unit2
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
