apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-unit2-pvc
  namespace: submission-portal
  labels:
    app: postgres
    unit: unit2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
