apiVersion: v1
kind: Service
metadata:
  name: submission-portal-unit1
  namespace: submission-portal
  labels:
    app: submission-portal
    unit: unit1
spec:
  selector:
    app: submission-portal
    unit: unit1
  ports:
  - port: 8080
    targetPort: 8080
    name: http
